---
- name: delete apt chache
  become: yes #bisa execute sudo
  become_user: root #ganti ke root
  become_method: su #ganti ke su, default root
  command: rm -vf /var/lib/apt/lists/*

- name: install on debian based linux
  become: yes #bisa execute sudo
  become_user: root
  become_method: su
  environment: 
    http_proxy: "{{ proxy_env }}"
    https_proxy: "{{ proxy_env }}"
  apt: name={{ item }} state=latest update_cache=true
  with_items:
   - apache2
  notify: 
   - restart apache2
  when: ansible_os_family  == "Debian"